/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package keylistener */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 5 "export.go"

#include <stdlib.h>
#include "hostapi.h"

static inline void host_log(bot_host_api_t* api, int level, char* msg) {
	if (api && api->log) api->log(level, msg);
}

static inline char* host_emit_event(bot_host_api_t* api, char* type, char* data, char* target) {
	if (api && api->emit_event) return api->emit_event(type, data, target);
	return NULL;
}

static inline void host_free(bot_host_api_t* api, void* ptr) {
	if (api && api->free) api->free(ptr);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) char* plugin_name(void);
extern __declspec(dllexport) uint32_t plugin_api_version(void);
extern __declspec(dllexport) void plugin_set_host(bot_host_api_t* api);
extern __declspec(dllexport) void plugin_free(void* ptr);
extern __declspec(dllexport) char* plugin_init(char* configJSON);
extern __declspec(dllexport) void plugin_start(void);
extern __declspec(dllexport) void plugin_stop(void);
extern __declspec(dllexport) char* plugin_get_actions(void);
extern __declspec(dllexport) char* plugin_call_action(char* name, char* argsJSON);

#ifdef __cplusplus
}
#endif
